server:
  port: 8080
  servlet:    context-path: /
    encoding:      charset: utf-8      force: true      enabled: true
  error:
      include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부 include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부
      include-stacktrace: always


spring:  mvc:    view:      prefix: /WEB-INF/views/      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bazigtest
    username: root
    password: root
        
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # 프로젝트를 실행할때 마다 테이블을 새로 만든다. 따라서 초기에는 create 이후에는 update로 바꿔놔야한다. 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #엔티티를 만들때, 즉 테이블을 만들때 변수명 그대로 테이블에 반영
      use-new-id-generator-mappings: false # jpa가 사용하는 기본 넘버링 전략을 따가지 않음.
    show-sql: true # 콘솔창에 보이는 유무
    properties: # 이게 없으면 콘솔창에 한줄로 보이지만, 이 값을 설정하면 예쁘게 나옴
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

  security:    oauth2:      client:        registration:          google:
            client-id: 94313580269-gd9df20s54solq0k61nn94qsm57c1ehf.apps.googleusercontent.com
            client-secret: FKVFvcQatN3HrwE8asYtrelQ
            scope:
            - email
            - profile
            
          facebook:
            client-id: 715575785778215
            client-secret: 483e42b2a2742a74c9129e563327e436
            scope:
            - email
            - public_profile
            
          naver:
            client-id: FiJuVwaSpzXE6264oUOR
            client-secret: m21JAUPY1C
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            #redirect-uri: http://localhost:8080/login/oauth2/code/naver
            redirect-uri: http://13.209.41.213:8080/login/oauth2/code/naver
          kakao:
            client-id: 34c4dd1b843bc1b79acfc1b6c119f767
            scope:
            - account_email
            - profile
            client-name: kakao
            authorization-grant-type: authorization_code
            #redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: http://13.209.41.213:8080/login/oauth2/code/kakao
            
        provider:
         naver:
           authorization-uri: https://nid.naver.com/oauth2.0/authorize
           token-uri: https://nid.naver.com/oauth2.0/token
           user-info-uri: https://openapi.naver.com/v1/nid/me
           user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.
         kakao:
           authorization-uri: https://kauth.kakao.com/oauth/authorize
           token-uri: https://kauth.kakao.com/oauth/token
           user-info-uri: https://kapi.kakao.com/v2/user/me
           user-name-attribute: kakao_account

OAuth2:
  key: bazig1234