server:
  port: 8000
  servlet:    context-path: /
    encoding:      charset: utf-8      force: true      enabled: true
  error:
      include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부 include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부
      include-stacktrace: always


spring:  mvc:    view:      prefix: /WEB-INF/views/      suffix: .jsp
      
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bazigtest
    username: bazigtest
    password: qpdlwlrm12
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # 프로젝트를 실행할때 마다 테이블을 새로 만든다. 따라서 초기에는 create 이후에는 update로 바꿔놔야한다. 
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #엔티티를 만들때, 즉 테이블을 만들때 변수명 그대로 테이블에 반영
      use-new-id-generator-mappings: false # jpa가 사용하는 기본 넘버링 전략을 따가지 않음.
    show-sql: true # 콘솔창에 보이는 유무
    properties: # 이게 없으면 콘솔창에 한줄로 보이지만, 이 값을 설정하면 예쁘게 나옴
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

cos:
  key: cos1234